// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxwvZVk29BLzKRGjgVm3xsXAp248A_oRo',
    appId: '1:802337643582:web:dc3512416dfb3edaf3056f',
    messagingSenderId: '802337643582',
    projectId: 'please-83f9a',
    authDomain: 'please-83f9a.firebaseapp.com',
    storageBucket: 'please-83f9a.appspot.com',
    measurementId: 'G-KXNX67WXDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTZCst77HHOLRigq6OrT1LL_CBUpzyJzA',
    appId: '1:802337643582:android:7319da943638113df3056f',
    messagingSenderId: '802337643582',
    projectId: 'please-83f9a',
    storageBucket: 'please-83f9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKwSMa1044QZJX3ny1j4yDGA0iZkdSy3Y',
    appId: '1:802337643582:ios:3fdcc9c7926acd5ef3056f',
    messagingSenderId: '802337643582',
    projectId: 'please-83f9a',
    storageBucket: 'please-83f9a.appspot.com',
    iosBundleId: 'com.example.wishlifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKwSMa1044QZJX3ny1j4yDGA0iZkdSy3Y',
    appId: '1:802337643582:ios:3fdcc9c7926acd5ef3056f',
    messagingSenderId: '802337643582',
    projectId: 'please-83f9a',
    storageBucket: 'please-83f9a.appspot.com',
    iosBundleId: 'com.example.wishlifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxwvZVk29BLzKRGjgVm3xsXAp248A_oRo',
    appId: '1:802337643582:web:6be8bd20f411c86ef3056f',
    messagingSenderId: '802337643582',
    projectId: 'please-83f9a',
    authDomain: 'please-83f9a.firebaseapp.com',
    storageBucket: 'please-83f9a.appspot.com',
    measurementId: 'G-MGH2XP0E1D',
  );
}
